package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// workflowTemplates maps a flavor to (filename, content).
var workflowTemplates = map[string]struct {
	filename string
	content  string
}{
	"pages":      {"pages.yml", pagesWorkflow},
	"jekyll":     {"jekyll.yml", jekyllWorkflow},
	"link-check": {"link-check.yml", linkCheckWorkflow},
}

func runGenerateWorkflow(args []string) error {
	// The flavor is an optional leading positional.
	var flavor string
	rest := args
	if len(args) > 0 && !strings.HasPrefix(args[0], "-") {
		flavor, rest = args[0], args[1:]
	}

	fs := flag.NewFlagSet("generate-workflow", flag.ExitOnError)
	var (
		out   = fs.String("out", "", "output file path (default: .github/workflows/<name>)")
		toOut = fs.Bool("stdout", false, "write to stdout instead of a file")
		force = fs.Bool("force", false, "overwrite the output file if it exists")
	)
	fs.Usage = func() {
		fmt.Fprintln(fs.Output(), "Usage: github-docs-cli generate-workflow <flavor> [flags]")
		fmt.Fprintf(fs.Output(), "\nFlavors: %s\n", strings.Join(workflowFlavors(), ", "))
		fmt.Fprintln(fs.Output(), "  pages       Deploy a static docs/ folder to GitHub Pages")
		fmt.Fprintln(fs.Output(), "  jekyll      Build docs/ with Jekyll and deploy to Pages")
		fmt.Fprintln(fs.Output(), "  link-check  Check Markdown links in docs/ on PRs")
		fs.PrintDefaults()
	}
	if err := fs.Parse(rest); err != nil {
		return err
	}
	if flavor == "" && fs.NArg() > 0 {
		flavor = fs.Arg(0)
	}
	if flavor == "" {
		fs.Usage()
		return fmt.Errorf("a flavor is required (%s)", strings.Join(workflowFlavors(), ", "))
	}

	tmpl, ok := workflowTemplates[flavor]
	if !ok {
		return fmt.Errorf("unknown flavor %q (supported: %s)", flavor, strings.Join(workflowFlavors(), ", "))
	}

	if *toOut {
		_, err := os.Stdout.WriteString(tmpl.content)
		return err
	}

	target := *out
	if target == "" {
		target = filepath.Join(".github", "workflows", tmpl.filename)
	}
	if !*force {
		if _, err := os.Stat(target); err == nil {
			return fmt.Errorf("%s already exists (use --force to overwrite or --stdout to print)", target)
		}
	}
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(target, []byte(tmpl.content), 0o644); err != nil {
		return err
	}
	fmt.Printf("wrote %s (%s workflow, %d bytes)\n", target, flavor, len(tmpl.content))
	return nil
}

func workflowFlavors() []string {
	names := make([]string, 0, len(workflowTemplates))
	for k := range workflowTemplates {
		names = append(names, k)
	}
	sort.Strings(names)
	return names
}

const pagesWorkflow = `# Deploy the docs/ folder to GitHub Pages as a static site.
# Generated by github-docs-cli (generate-workflow pages).
name: Deploy docs to Pages

on:
  push:
    branches: [main]
    paths: ["docs/**"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs
      - id: deployment
        uses: actions/deploy-pages@v4
`

const jekyllWorkflow = `# Build the docs/ folder with Jekyll and deploy to GitHub Pages.
# Generated by github-docs-cli (generate-workflow jekyll).
name: Build & deploy Jekyll docs

on:
  push:
    branches: [main]
    paths: ["docs/**"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./_site
      - uses: actions/upload-pages-artifact@v3

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
`

const linkCheckWorkflow = `# Check Markdown links in docs/ on pull requests.
# Generated by github-docs-cli (generate-workflow link-check).
name: Docs link check

on:
  pull_request:
    paths: ["docs/**", "**/*.md"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --no-progress --verbose "docs/**/*.md" "*.md"
          fail: true
`
