sonar.projectKey=jhl-labs_github-docs-cli
sonar.projectName=jhl-labs/github-docs-cli
sonar.sources=.
sonar.exclusions=**/.git/**,**/node_modules/**,**/reports/**,**/coverage/**,**/dist/**,**/build/**,**/.next/**,**/vendor/**
